spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: password
      database: messaging
      port: 27017


broadcast:
  in: IN.BROADCAST
  out: OUT.BROADCAST
  exchange: KE.EXCH
  prefetch: 10
  routing-key: BROAD.KEY