spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: admin
#      password: password
      database: messaging
      port: 27017
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

broadcast:
  in: IN.BROADCAST
  out: OUT.OUTGOING
  out-exchange: KE.EXCH
  delay-exchange: DELAY.EXCH
  prefetch: 10
  consumerCount: 2
  routing-key: BROAD.KEY
  out_key: OUT.KEY
  message:
    active-message: 1
    active-status: 1
  time:
    format: yyyy-MM-dd HH:mm:ss.SSS
    timezone: UTC+3
  async:
    threadPoolSize: 10
    maxThreadPoolSize: 10

logging:
  level:
    org:
      springframework:
        data: debug