spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: admin
#      password: password
      database: messaging
      port: 27017
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

transactional:
  queue:
    in: IN.TRANSACTIONAL
    out: OUT.OUTGOING
    out-exchange: KE.EXCH
    prefetch: 10
    consumerCount: 5
    routing-key: TRANSACTIONAL.KEY
    out_key: OUT.KEY
  time:
    format: yyyy-MM-dd HH:mm:ss.SSS
    timezone: UTC+3
  async:
    threadPoolSize: 10
    maxThreadPoolSize: 10

logging:
  level:
    org:
      springframework:
        data: debug