spring:
  application:
    name: BroadCast
  cloud:
    config:
      uri: http://localhost:8888
      password: password
      username: user
      fail-fast: true
  profiles:
    active: native
management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 8081
#logging:
#  level:
#    org.springframework.boot: DEBUG

