spring:
  application:
    name: Upload-service
  datasource:
    url: jdbc:mysql://localhost:3306/messagingupload
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
       hibernate:
         format_sql: true
         dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  batch:
    initialize-schema: always

server:
      port: 8005

upload:
  batch-files-config:
    PROPERTY_SOURCE_FILE_PATH: /home/lugonzo/intellij/messagingSystemData/uploaddata1.xlsx
    chunckSize: 500
    uuidLength: 6
  rabbit:
    inbound_upload_queue: INBOUNDUPLOAD.QUEUE
    inbound_upload_exchange: INBOUNDUPLOAD.EXCHANGE
    inbound_upload_routing_key: INBOUNDUPLOAD.ROUTEKEY
    outbound_upload_queue: OUTBOUNDUPLOAD.QUEUE
    outbound_upload_exchange: OUTBOUNDUPLOAD.EXCHANGE
    outbound_upload_routing_key: OUTBOUNDUPLOAD.ROUTEKEY

